spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb

    username: root
    password: srirajan1969
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true